  spring:
    application:
      name: config
    profiles:
      active: git
    cloud:
      config:
        server:
          git:
            uri: ${GIT_URI:https://github.com/DatP2K3/4man_fashion_config.git}
            default-label: main
            timeout: 5
            clone-on-start: true
            force-pull: true
            username: ${GIT_USERNAME:DATP2K3}
            password: ${GIT_PASSWORD}

  server:
    port: ${SERVER_PORT:6969}

  encrypt:
    key: ${ENCRYPT_KEY}

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true