name: datp2k3_microservice
services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    mem_limit: 384m
    cpus: 0.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 4man_network

  rabbitmq:
    image: rabbitmq:4.1.0-rc.2-management
    container_name: my_rabbitmq
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    restart: unless-stopped
    networks:
      - 4man_network

  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: my_elasticsearch
    restart: always
    mem_limit: 768m
    cpus: 0.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 50s
    networks:
      - 4man_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: my_keycloak
    restart: always
    mem_limit: 384m
    cpus: 0.5
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/4manfashion:/opt/keycloak/themes/4manfashion
    depends_on:
      - postgres
    networks:
      - 4man_network

  discovery-service:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: my_discovery_service
    image: datp2k3/discovery_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  storage-service:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: my_storage_service
    image: datp2k3/storage_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8080:8080"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/storage_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWK_URI=http://keycloak:8080/realms/IamService
      - EUREKA_URL=http://discovery-service:8761/eureka
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: my_payment_service
    image: datp2k3/payment_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8008:8008"
    environment:
      - SERVER_PORT=8008
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/payment_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_URL=http://discovery-service:8761/eureka
      - JWK_URI=http://keycloak:8080/realms/IamService
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - VNPAY_TMNCODE=${VNPAY_TMNCODE}
      - VNPAY_SECRET_KEY=${VNPAY_SECRET_KEY}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - PAYMENT_REDIRECT_URL=${PAYMENT_REDIRECT_URL}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  dashboard-service:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: my_dashboard_service
    image: datp2k3/dashboard_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "2222:2222"
    environment:
      - SERVER_PORT=2222
      - JWK_URI=http://keycloak:8080/realms/IamService
      - EUREKA_URL=http://discovery-service:8761/eureka
      - ORDER_SERVICE_URL=http://my_order_service:6666
      - PROFILE_SERVICE_URL=http://my_profile_service:9999
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  profile-service:
    build:
      context: ./profile
      dockerfile: Dockerfile
    container_name: my_profile_service
    image: datp2k3/profile_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "9999:9999"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/profile_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - JWK_URI=http://keycloak:8080/realms/IamService
      - EUREKA_URL=http://discovery-service:8761/eureka
      - STORAGE_SERVICE_URL=http://my_storage_service:8080
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  public-info-service:
    build:
      context: ./public-info
      dockerfile: Dockerfile
    container_name: my_public_info_service
    image: datp2k3/public_info_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "6565:6565"
    environment:
      - JWK_URI=http://keycloak:8080/realms/IamService
      - EUREKA_URL=http://discovery-service:8761/eureka
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/public_info_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=6565
      - STORAGE_SERVICE_URL=http://my_storage_service:8080
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  notification-service:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: my_notification_service
    image: datp2k3/notification_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "3333:3333"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/noti
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - SERVER_PORT=3333
      - EUREKA_URL=http://discovery-service:8761/eureka
      - PRODUCT_SERVICE_URL=http://my_product_service:8765
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWK_URI=http://keycloak:8080/realms/IamService
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: my_product_service
    image: datp2k3/product_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8765:8765"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/product_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - SERVER_PORT=8765
      - EUREKA_URL=http://discovery-service:8761/eureka
      - JWK_URI=http://keycloak:8080/realms/IamService
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: my_order_service
    image: datp2k3/order_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "6666:6666"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/order_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - EUREKA_URL=http://discovery-service:8761/eureka
      - CART_SERVICE_URL=http://my_cart_service:8000
      - PROFILE_SERVICE_URL=http://my_profile_service:9999
      - PUBLIC_INFO_SERVICE_URL=http://my_public_info_service:6565
      - PAYMENT_SERVICE_URL=http://my_payment_service:8008
      - GHN_URL=${GHN_URL}
      - GHN_TOKEN=${GHN_TOKEN}
      - JWK_URI=http://keycloak:8080/realms/IamService
      - GHN_ID=${GHN_ID}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: my_gateway_service
    image: datp2k3/gateway_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8686:8686"
    environment:
      - STORAGE_HOST=my_storage_service
      - SERVER_PORT=8686
      - JWK_URI=http://keycloak:8080/realms/IamService
      - EUREKA_URL=http://discovery-service:8761/eureka
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - 4man_network

  elasticsearch-service:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: my_elasticsearch_service
    image: datp2k3/elasticsearch_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "5566:5566"
    environment:
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - SERVER_PORT=5566
      - EUREKA_URL=http://discovery-service:8761/eureka
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - 4man_network

  cart-service:
    build:
      context: ./cart
      dockerfile: Dockerfile
    container_name: my_cart_service
    image: datp2k3/cart_service
    restart: always
    mem_limit: 256m
    cpus: 0.25
    ports:
      - "8000:8000"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://postgres:5432/cart_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=8000
      - EUREKA_URL=http://discovery-service:8761/eureka
      - JWK_URI=http://keycloak:8080/realms/IamService
      - PRODUCT_SERVICE_URL=http://my_product_service:8765
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - 4man_network

volumes:
  postgres_data:
  elasticsearch_data:
  keycloak_data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  4man_network: