changeLogFile=src/main/resources/db/changelog-master.xml
changeSetAuthor=DatDZ2k3
logLevel=debug
url=jdbc:postgresql://localhost:5433/profile_db
username=postgres
password=14062003
driver=org.postgresql.Driver
diffExcludeObjects=table:databasechangelog,table:databasechangeloglock
referenceUrl=hibernate:spring:com.evo.profile.infrastructure.persistence.entity?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
