spring:
  application:
    name: cart-service

  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/cart_db}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:8180/realms/IamService}

  doc:
    swagger-ui:
      path: /swagger-doc/cart/swagger-ui.html
    api-docs:
      path: /swagger-doc/v3/api-docs/cart

server:
  port: ${SERVER_PORT:8000}

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

app:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8765}